CREATE TABLE ROOMS
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT ROOMS_PK PRIMARY KEY (ID),
	NUMBER_OF_GUESTS NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	BREAKFAST_INCLUDED NUMBER NOT NULL,
	PETS_ALLOWED NUMBER NOT NULL,
	DATE_AVAILABLE_FROM DATE NOT NULL,
	ID_HOTELS NUMBER,
	FOREIGN KEY (ID_HOTELS) REFERENCES HOTELS (ID)
);