CREATE TABLE ROOMS
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT ROOMS_PK PRIMARY KEY (ID),
	NUMBER_OF_GUESTS NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	BREAKFAST_INCLUDED NUMBER(1) CHECK (BREAKFAST_INCLUDED IN (0, 1)),
	PETS_ALLOWED NUMBER(1) CHECK (PETS_ALLOWED IN (0, 1)),
	DATE_AVAILABLE_FROM DATE,
	ID_HOTELS NUMBER,
	FOREIGN KEY (ID_HOTELS) REFERENCES HOTELS (ID)
);