CREATE TABLE ORDERS
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT ORDERS_PK PRIMARY KEY (ID),
	ROOM_ID NUMBER NOT NULL,
	DATE_FROM DATE,
	DATE_TO DATE,
	MONEY_PAID NUMBER,
	ID_USERS NUMBER,
	FOREIGN KEY (ID_USERS) REFERENCES USERS (ID)
);