CREATE TABLE HOTELS
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT HOTELS_PK PRIMARY KEY (ID),
	NAME NVARCHAR2(100) NOT NULL,
	COUNTRY NVARCHAR2(40) NOT NULL,
	CITY NVARCHAR2(40) NOT NULL,
	STREET NVARCHAR2(40)
);