CREATE TABLE FILES
(
	id NUMBER NOT NULL ENABLE,
	CONSTRAINT FILES_PK PRIMARY KEY (id),
	filesName NVARCHAR2(20) NOT NULL,
    filesFormat NVARCHAR2(5) NOT NULL,
	filesSize NUMBER NOT NULL,
    id_storage NUMBER,
    FOREIGN KEY (id_storage) REFERENCES STORAGE (id)
);