CREATE TABLE FILES
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT FILES_PK PRIMARY KEY (ID),
	FILESNAME NVARCHAR2(20) NOT NULL,
	FILESFORMAT NVARCHAR2(5) NOT NULL,
	FILESSIZE NUMBER NOT NULL,
	ID_STORAGE NUMBER,
	FOREIGN KEY (ID_STORAGE) REFERENCES STORAGE (ID)
);