CREATE TABLE STORAGE
(
	ID NUMBER NOT NULL ENABLE,
	CONSTRAINT STORAGE_PK PRIMARY KEY (ID),
	FORMATSSUPPORTED NVARCHAR2(100) NOT NULL,
	STORAGECOUNTRY NVARCHAR2(40) NOT NULL,
	STORAGESIZE NUMBER NOT NULL
);