CREATE TABLE STORAGE
(
	id NUMBER NOT NULL ENABLE,
	CONSTRAINT STORAGE_PK PRIMARY KEY (id),
	formatsSupported NVARCHAR2(100) NOT NULL,
    storageCountry NVARCHAR2(40) NOT NULL,
	storageSize NUMBER NOT NULL
);